my_file = open('file_2.txt', 'r')
c = my_file.read()
print(f'в ФАЙЛЕ: \n {c}')
my_file = open('file_2.txt', 'r')
c = my_file.readlines()
print(f'Количество строк в файле - {len(c)}')
my_file = open('file_2.txt', 'r')
c = my_file.readlines()
for i in range(len(c)):
print(f'Количество символов {i + 1} - ой строки {len(c[i])}')
my_file = open('file_2.txt', 'r')
c = my_file.read()
c = c.split()
print(f' количество слов - {len(c)}')
my_file.close()